In [75]:
import numpy as np
import matplotlib.pyplot as plt

In [76]:
X_data = np.genfromtxt('X_data.csv', delimiter=',')
Y_data = np.genfromtxt('Y_data.csv', delimiter=',')
Y_data = Y_data.reshape(712,1)
Y_data = Y_data.T
X_dev_data = np.genfromtxt('X_dev_data.csv', delimiter=',')
Y_dev_data = np.genfromtxt('Y_dev_data.csv', delimiter=',')
Y_dev_data = Y_dev_data.reshape(179,1)

In [77]:
layers_dims = [10, 8, 6, 4,2,1]

In [78]:
def initialize_parameters_deep(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the network

    for l in range(1, L):
   
        
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
      
      
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [79]:
#parameters = initialize_parameters_deep(layers_dims)
#print(parameters["W1"])

In [80]:
#initialize parameter
np.random.seed(3)
W1 = np.random.rand(8, 10) * 0.01
b1 = np.zeros((8,1))
W2 = np.random.rand(1, 8) * 0.01
b2 = np.zeros((1,1))

In [81]:
def forward_propagation(W,b,x):
    z = np.dot(W,x) + b
    return np.maximum(0,z),z

In [82]:
def forward_propagation_L(W,b,x):
    z = np.dot(W,x) + b
    return 1 / (1 + np.exp(-z))

In [83]:
def deriv_ReLU(Z):
    return Z>0

In [84]:
W1

array([[0.00550798, 0.00708148, 0.00290905, 0.00510828, 0.00892947,
        0.00896293, 0.00125585, 0.00207243, 0.00051467, 0.0044081 ],
       [0.00029876, 0.00456833, 0.00649144, 0.00278487, 0.00676255,
        0.00590863, 0.00023982, 0.00558854, 0.00259252, 0.00415101],
       [0.00283525, 0.00693138, 0.00440454, 0.00156868, 0.00544649,
        0.00780315, 0.00306364, 0.00221958, 0.00387971, 0.00936384],
       [0.00975995, 0.00672384, 0.00902834, 0.00845751, 0.00377994,
        0.00092217, 0.00653411, 0.00557841, 0.00361565, 0.00225055],
       [0.0040652 , 0.0046894 , 0.00269236, 0.00291793, 0.00457686,
        0.00860534, 0.00586253, 0.00283488, 0.00277978, 0.00454622],
       [0.0020541 , 0.00201379, 0.00514035, 0.00087229, 0.00483586,
        0.00362176, 0.00707687, 0.00746746, 0.00691093, 0.0068918 ],
       [0.003736  , 0.00668135, 0.00339849, 0.00572794, 0.00325807,
        0.00445145, 0.00061529, 0.00242675, 0.00971603, 0.00230584],
       [0.00691478, 0.00650477, 0.0072393

In [85]:
W2

array([[0.00129294, 0.00553278, 0.00187815, 0.00952101, 0.00681612,
        0.0054102 , 0.00707181, 0.00263887]])

In [86]:
b1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [87]:
b2

array([[0.]])

In [104]:
learning_rate = .1

In [127]:
def test(W1,W2,b1,b2,X,Y_test):
    a1,cashe1 = forward_propagation(W1,b1,X.T)
    a2 = forward_propagation_L(W2,b2,a1)
    Y_pred = []
    for i in range(a2.shape[1]):
        if a2[0][i]>0.5:
            Y_pred.append(1.0)
        else:
            Y_pred.append(0.0)
    
    correct = 0
    for i in range (len(Y_pred)):
        if Y_pred[i]==Y_test[i][0]:
            correct+=1
    
    return correct/len(Y_pred)*100

In [131]:
for i in range(10000):
    a1,cache1 = forward_propagation(W1,b1,X_data.T)
    a2 = forward_propagation_L(W2,b2,a1)
    cost = (-1/712)*np.sum(Y_data*np.log(a2)+(1-Y_data)*np.log(1-a2))

    
    dz2 = (a2 - Y_data)
    dW2 = np.dot(dz2,a1.T)/712
    db2 = np.sum(dz2)/712

    dz1 =  W2.T.dot(dz2) * deriv_ReLU(cache1)
    dW1 = np.dot(dz1,X_data)/712
    db1 = np.sum(dz1)/712
    
    W2=W2 - learning_rate*dW2
    b2 = b2 - learning_rate*db2
    W1=W1 - learning_rate*dW1
    b1 = b1 - learning_rate*db1
    
    acc = test (W1,W2,b1,b2,X_dev_data,Y_dev_data)
    print("Iteration",i,"--Cost:",cost,"Accuracy:",acc)

    

Iteration 0 --Cost: 0.38062181108105075 Accuracy: 79.88826815642457
Iteration 1 --Cost: 0.3806438796669189 Accuracy: 79.88826815642457
Iteration 2 --Cost: 0.3806184930669298 Accuracy: 79.88826815642457
Iteration 3 --Cost: 0.3806441946420314 Accuracy: 79.88826815642457
Iteration 4 --Cost: 0.38061754393634883 Accuracy: 79.88826815642457
Iteration 5 --Cost: 0.38063965398451544 Accuracy: 79.88826815642457
Iteration 6 --Cost: 0.3806206754489822 Accuracy: 79.88826815642457
Iteration 7 --Cost: 0.38065138145377675 Accuracy: 79.88826815642457
Iteration 8 --Cost: 0.3806154742111511 Accuracy: 79.88826815642457
Iteration 9 --Cost: 0.3806100259454862 Accuracy: 79.88826815642457
Iteration 10 --Cost: 0.3806203463134551 Accuracy: 79.88826815642457
Iteration 11 --Cost: 0.3806542867174369 Accuracy: 79.88826815642457
Iteration 12 --Cost: 0.38061660570056577 Accuracy: 79.88826815642457
Iteration 13 --Cost: 0.38061411135602136 Accuracy: 79.88826815642457
Iteration 14 --Cost: 0.3806423479572896 Accuracy: 79

In [109]:
W1

array([[-0.67300228,  0.45586485,  0.2040723 , -0.20685962,  0.0862823 ,
         0.55381376, -0.54359497, -0.06593304,  0.02709989,  0.0042952 ],
       [-0.89816321, -0.26842036,  0.25422129,  0.09484807, -0.44984139,
         0.3329217 , -0.32677325,  0.0016676 , -0.04926248, -0.04923048],
       [-0.18960935,  0.46052164,  0.09297517, -0.42095889,  0.30416871,
         0.81273621, -0.80186943,  0.16127622,  0.2073947 , -0.31674572],
       [-0.15236231, -0.32990996,  0.09663838,  0.53269872, -0.3952957 ,
        -0.12878868,  0.13624496,  0.03500606, -0.10598314, -0.19505714],
       [-0.80552124, -0.24159099,  0.22546452,  0.08762271, -0.404607  ,
         0.29885752, -0.28438965,  0.00229868, -0.04149232, -0.04476751],
       [-0.63382437,  0.42835029,  0.19377581, -0.19275051,  0.07811316,
         0.51976539, -0.50906676, -0.05487634,  0.0286629 ,  0.0098777 ],
       [-0.96606561, -0.28812303,  0.27467645,  0.10062497, -0.48316837,
         0.36071647, -0.35564973,  0.00660708

In [110]:
W2

array([[ 0.44035001,  0.57399154,  0.77091205,  1.94576282,  0.44218934,
         0.36327372,  0.65418915, -2.2935708 ]])

In [111]:
b1

array([[-0.05617895],
       [-0.05617895],
       [-0.05617895],
       [-0.05617895],
       [-0.05617895],
       [-0.05617895],
       [-0.05617895],
       [-0.05617895]])

In [112]:
b2

array([[-1.95814122]])

In [132]:
print(test(W1,W2,b1,b2,X_dev_data,Y_dev_data))

81.00558659217877


In [133]:
X_test_data = np.genfromtxt('X_test_data.csv', delimiter=',')
a1,cache1 = forward_propagation(W1,b1,X_test_data.T)
a2 = forward_propagation_L(W2,b2,a1)
Y_pred = []
for i in range(a2.shape[1]):
    if a2[0][i]>0.5:
        Y_pred.append(1.0)
    else:
        Y_pred.append(0.0)
    
print(Y_pred)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0,

In [134]:
import pandas as pd
dict = {'Survived': Y_pred}
     
df = pd.DataFrame(dict)
df.to_csv('Output.csv')

In [135]:
df.columns

Index(['Survived'], dtype='object')